In [1]:
import torch

张量表示由一个数值组成的数组（可能多维）

In [2]:
x = torch.arange(12)
# arange若给出步长，则必须指定start
y = torch.arange(1,12,3)
x,y

(tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]),
 tensor([ 1,  4,  7, 10]))

`张量shape属性访问张量的形状和张量中元素的总数

In [3]:
x.shape

torch.Size([12])

In [4]:
x.numel()

12

仅改变张量形状,reshape函数

In [5]:
X = x.reshape(3,4)
X,X.numel()

(tensor([[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]]),
 12)

全0、全1、其他常量或者特定分布中随机采样的数字

In [6]:
torch.zeros((2,3,5))

tensor([[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]])

In [7]:
torch.ones((2,3,5))

tensor([[[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]]])

In [8]:
torch.randn(2,3,5)

tensor([[[ 0.9768,  0.1412, -1.1905, -1.0712,  0.7013],
         [-1.3224,  0.5638,  1.5141, -1.7450, -0.1546],
         [-2.6319,  0.7899,  0.6327,  0.9940, -1.1337]],

        [[-0.4985,  0.7603,  0.4055,  1.4975,  0.5728],
         [-0.5418,  1.6844,  0.7573,  0.4713,  0.6117],
         [ 0.9738,  0.6243, -0.6625,  0.2649,  0.7867]]])

Python列表——> 张量

In [9]:
x = [[1,3,5,7,9],[2,4,6,8,0]]
torch.tensor(x)

tensor([[1, 3, 5, 7, 9],
        [2, 4, 6, 8, 0]])

常见标准运算符都升级为按元素运算

In [10]:
x = torch.tensor([0,3,5,7],dtype = torch.float32)
y = torch.tensor([2,2,2,2])
x+y, x-y, x*y, x/y, x**y

(tensor([2., 5., 7., 9.]),
 tensor([-2.,  1.,  3.,  5.]),
 tensor([ 0.,  6., 10., 14.]),
 tensor([0.0000, 1.5000, 2.5000, 3.5000]),
 tensor([ 0.,  9., 25., 49.]))

按元素方式应用更多计算

In [11]:
torch.exp(x)

tensor([1.0000e+00, 2.0086e+01, 1.4841e+02, 1.0966e+03])

张量连结

In [12]:
X = torch.arange(12, dtype=torch.float32).reshape((3,4))
Y = torch.tensor([[2,1.4,0.8,3.1],[4,3.6,9.2,10],[12,11,8.8,2]])
# dim = 0 ——> 行增加 / dim = 1 ——> 列增加
torch.cat((X,Y),dim=0),torch.cat((X,Y),dim=1)

(tensor([[ 0.0000,  1.0000,  2.0000,  3.0000],
         [ 4.0000,  5.0000,  6.0000,  7.0000],
         [ 8.0000,  9.0000, 10.0000, 11.0000],
         [ 2.0000,  1.4000,  0.8000,  3.1000],
         [ 4.0000,  3.6000,  9.2000, 10.0000],
         [12.0000, 11.0000,  8.8000,  2.0000]]),
 tensor([[ 0.0000,  1.0000,  2.0000,  3.0000,  2.0000,  1.4000,  0.8000,  3.1000],
         [ 4.0000,  5.0000,  6.0000,  7.0000,  4.0000,  3.6000,  9.2000, 10.0000],
         [ 8.0000,  9.0000, 10.0000, 11.0000, 12.0000, 11.0000,  8.8000,  2.0000]]))

逻辑运算

In [13]:
X == Y, X > Y, X < Y

(tensor([[False, False, False, False],
         [ True, False, False, False],
         [False, False, False, False]]),
 tensor([[False, False,  True, False],
         [False,  True, False, False],
         [False, False,  True,  True]]),
 tensor([[ True,  True, False,  True],
         [False, False,  True,  True],
         [ True,  True, False, False]]))

对张量所有元素求和

In [14]:
X.sum()

tensor(66.)

广播机制——处理形状不同，但维度相同的张量

In [15]:
a = torch.arange(3).reshape((3,1))
b = torch.arange(4).reshape((1,4))
a,b

(tensor([[0],
         [1],
         [2]]),
 tensor([[0, 1, 2, 3]]))

In [16]:
a + b

tensor([[0, 1, 2, 3],
        [1, 2, 3, 4],
        [2, 3, 4, 5]])

In [17]:
a = torch.arange(12).reshape((3,4,1))
b = torch.arange(4).reshape((1,1,4))
a,b

(tensor([[[ 0],
          [ 1],
          [ 2],
          [ 3]],
 
         [[ 4],
          [ 5],
          [ 6],
          [ 7]],
 
         [[ 8],
          [ 9],
          [10],
          [11]]]),
 tensor([[[0, 1, 2, 3]]]))

In [18]:
a + b

tensor([[[ 0,  1,  2,  3],
         [ 1,  2,  3,  4],
         [ 2,  3,  4,  5],
         [ 3,  4,  5,  6]],

        [[ 4,  5,  6,  7],
         [ 5,  6,  7,  8],
         [ 6,  7,  8,  9],
         [ 7,  8,  9, 10]],

        [[ 8,  9, 10, 11],
         [ 9, 10, 11, 12],
         [10, 11, 12, 13],
         [11, 12, 13, 14]]])

张量的切片

In [19]:
X[-1],X[:2]

(tensor([ 8.,  9., 10., 11.]),
 tensor([[0., 1., 2., 3.],
         [4., 5., 6., 7.]]))

指定索引写入元素

In [20]:
X[1,2] = 9
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  9.,  7.],
        [ 8.,  9., 10., 11.]])

In [21]:
X[0:2,:] = 12
X

tensor([[12., 12., 12., 12.],
        [12., 12., 12., 12.],
        [ 8.,  9., 10., 11.]])

内存问题

In [22]:
before = id(Y)
Y = Y + X # 分配新内存
id(Y) == before

False

In [23]:
before = id(X)
X += Y # 原地操作
id(X) == before

True

In [24]:
Z = torch.zeros_like(Y)
print('id(Z):', id(Z))
Z[:] = X + Y
print('id(Z):', id(Z))

id(Z): 2041903210880
id(Z): 2041903210880


Numpy 与 torch张量 互换

In [25]:
A = X.numpy()
B = torch.tensor(A)
type(A),type(B)

(numpy.ndarray, torch.Tensor)

将大小为1的张量转换为python标量

In [26]:
a = torch.tensor([3.5])
a,a.item(),float(a),int(a)

(tensor([3.5000]), 3.5, 3.5, 3)