In [1]:
import numpy as np

In [2]:
times = [1,3,5,7,9]

np.array(times).cumsum(), np.array(times).cumsum().tolist()

(array([ 1,  4,  9, 16, 25]), [1, 4, 9, 16, 25])

In [3]:
x = np.array([1,3,5,7])

x**2

array([ 1,  9, 25, 49])

In [4]:
import torch
import random

In [5]:
x = torch.arange(50)

In [6]:
def test(x):
    indices = list(range(len(x)))
    random.shuffle(indices)
    for i in range(0,len(x),4):
        batch_indices = torch.tensor(indices[i:min(i+4,len(x))])
        random_x = x[batch_indices]
        yield x[batch_indices]

random_x = test(x)
random_x

<generator object test at 0x00000291851F0120>

array([ True, False, False, False])